### ISSUE TITLE
Support custom parameter annotations

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-codegen#117]
Example:
```
"size": {
  "name": "size",
  "schema": {
    "maximum": 500,
    "minimum": 1,
    "type": "integer"
  },
  "in": "query",
  "required": false,
  "x-annotations": [
    "@javax.validation.constraints.Min(1)"
    "@javax.validation.constraints.Max(500)"
  ]
}
```
Possibly adding the validation annotations automatically, if configured.

**Comment by EricWittmann** [comment]
It might be nice to figure out the validation constraints based on the schema rather than duplicate them in the annotations (but obviously support both).

**Comment by MikeEdgar** [comment]
I can take a look at this one if no objection. I think any upcoming POJO generation changes shouldn't impact it.

**Comment by EricWittmann** [comment]
![](https://media.tenor.com/oj7sLgfFkHQAAAAC/make-it-so-jean-luc-picard.gif)
