### ISSUE TITLE
The `byte` format for a `string` type, to host base64-encoded, is not represented as bytes array

### ISSUE THREAD

**Issue by ppatierno** [Apicurio/apicurio-codegen#130]
I was comparing the apicurio-codegen with the openapi generator and found the following difference.
A property in our OpenAPI specification is like this:

```json
"value": {
      "format": "byte",
      "type": "string",
      "description": "The header value in binary format, base64-encoded"
}
```

The openapi generator generates a field like this `byte[] value;` by honouring the requested "byte" as string format that by OpenAPI specification is `byte – base64-encoded characters, for example, U3dhZ2dlciByb2Nrcw==` as you can read [here](https://swagger.io/docs/specification/data-models/data-types/).
With apicurio-codegen I get a plain `String value;` field which sounds not to be correct to me.

**Comment by andreaTP** [comment]
You are right, fixed in #132 

`inline` doesn't apply in this very case.
